services:
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
    container_name: ${PROJECT_NAME}_php
    user: "${UID}:${GID}"
    volumes:
      - ${PS_SOURCES_DIR}:/var/www/html
    networks:
      - ps_network

  web:
    build:
      context: .docker/apache
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_web
    ports:
      - "${WEB_HTTP_PORT}:80"
      - "${WEB_HTTPS_PORT}:443"
    volumes:
      - ${PS_SOURCES_DIR}:/var/www/html
    depends_on:
      - php
    networks:
      - ps_network

  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${PROJECT_NAME}_db
    user: "${UID}:${GID}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ${PS_DB_DIR}:/var/lib/mysql
    networks:
      - ps_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: ${DOCKER_PLATFORM}
    container_name: ${PROJECT_NAME}_phpmyadmin
    user: "${UID}:${GID}"
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${PROJECT_NAME}_db
    depends_on:
      - db
    networks:
      - ps_network

  mailpit:
    image: axllent/mailpit
    container_name: ${PROJECT_NAME}_mailpit
    user: "${UID}:${GID}"
    restart: always
    ports:
      - "${MAILPIT_PORT}:8025"
    volumes:
      - ${PS_LOGS_DIR}/mailpit:/var/log
    networks:
      - ps_network

  node:
    image: node:${NODE_VERSION}
    container_name: ${PROJECT_NAME}_node
    user: "${UID}:${GID}"
    volumes:
      - ${PS_SOURCES_DIR}:/var/www/html
      - ${PS_LOGS_DIR}/node:/var/log
    working_dir: /var/www/html/themes/${THEME_NAME}
    command: tail -f /dev/null
    networks:
      - ps_network

networks:
  ps_network:
    name: ${PROJECT_NAME}_network
    driver: bridge